# Position Control
joint1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint1
    pid: {p: 50.0, i: 0.01, d: 0.0}

joint2_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint2
    pid: {p: 50.0, i: 0.01, d: 0.0}
