# joint (actionlib) trajectory controller
# check http://wiki.ros.org/joint_trajectory_controller

traj_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2

    gains: # Required because we're controlling an velocity interface
      joint1: {p: 100,  d: 0.1, i: 0.0, i_clamp: 1}
      joint2: {p: 100,  d: 0.1, i: 0.0, i_clamp: 1}

    constraints:
      goal_time: 4.0
      stopped_velocity_tolerance: 1.0
      joint1:
        goal: 0.5
        trajectory: 1.0
      joint2:
        goal: 0.5
        trajectory: 1.0

    stop_trajectory_duration: 1.0
