# joint (actionlib) trajectory controller
# check http://wiki.ros.org/joint_trajectory_controller

traj_controller:
    type: velocity_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2

    gains:
      joint1: {p: 500.0, i: 0.1, d: 1.0, i_clamp: 10}
      joint2: {p: 500.0, i: 0.1, d: 1.0, i_clamp: 10}

    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 2.0
      joint1:
        goal: 0.7
        trajectory: 1.5
      joint2:
        goal: 0.7
        trajectory: 1.5

    stop_trajectory_duration: 2.0
