<?xml version="1.0"?>
<robot name="acrobat" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Math properties -->
  <xacro:property name="PI" value="3.141592653589793" />

  <!-- link properties -->
  <xacro:property name="link_mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="link_width" value="0.1" /> <!-- link square dimensions (link_widthxlink_width) -->
  
  <!-- link1 properties -->
  <xacro:property name="link1_name" value="link1" />
  <xacro:property name="link1_height" value="3.0" />
  <xacro:property name="link1_color" value="grey" />
  
  <!-- link2 properties -->
  <xacro:property name="link2_name" value="link2" />
  <xacro:property name="link2_height" value="2.0" />
  <xacro:property name="link2_color" value="green" />

  <!-- joint properties -->
  <xacro:property name="joint_lower_limit" value="${-PI / 2.0}" />
  <xacro:property name="joint_upper_limit" value="${PI / 2.0}" />
  <xacro:property name="joint_effort" value="1000.0" />
  <xacro:property name="joint_velocity" value="0.5" />
  
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find acrobat_description)/urdf/materials.urdf.xacro" />

  <!-- link macro -->
  <xacro:macro name="link_macro" params="link_name link_height link_color">
    <link name="${link_name}">
      <visual>
        <origin xyz="${link_height/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${link_height} ${link_width} ${link_width}"/>
        </geometry>
        <material name="${link_color}"/>
      </visual>

      <collision>
        <origin xyz="${link_height/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${link_height} ${link_width} ${link_width}"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="${link_height/2} 0 0" rpy="0 0 0"/>
        <mass value="${link_mass}"/>
        <inertia
            ixx="${link_mass / 12.0 * (link_width*link_width + link_height*link_height)}" ixy="0.0" ixz="0.0"
            iyy="${link_mass / 12.0 * (link_height*link_height + link_width*link_width)}" iyz="0.0"
            izz="${link_mass / 12.0 * (link_width*link_width + link_width*link_width)}"/>
      </inertial>
    </link>
  </xacro:macro>

  <!-- joint macro -->
  <xacro:macro name="joint_macro" params="joint_name parent_link child_link parent_link_height">
    <joint name="${parent_link}_to_${child_link}_joint" type="revolute">
      <parent link="${parent_link}"/>
      <child link="${child_link}"/>
      <origin xyz="${parent_link_height} 0 ${parent_link_height - link_width / 2.0}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.7"/>
      <limit effort="${joint_effort}" lower="${joint_lower_limit}" upper="${joint_upper_limit}" velocity="${joint_velocity}"/>
    </joint>

    <transmission name="${joint_name}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${joint_name}">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${joint_name}_actuator">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <!-- link 0, 1 -->
  <link name="world"/>
  <link name="dummy_link"/>
  
  <!-- links 2, 3 -->
  <xacro:link_macro link_name="${link1_name}" link_height="${link1_height}" link_color="${link1_color}" />
  <xacro:link_macro link_name="${link2_name}" link_height="${link2_height}" link_color="${link2_color}" />

  <!-- joint0 -->
  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="dummy_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- joints 1, 2 -->
  <xacro:joint_macro joint_name="joint1" parent_link="dummy_link" child_link="${link1_name}" parent_link_height="0" />
  <xacro:joint_macro joint_name="joint2" parent_link="${link1_name}" child_link="${link2_name}" parent_link_height="${link1_height}" />

  <!-- gazebo related tags -->
  <xacro:include filename="$(find acrobat_description)/urdf/acrobat_gazebo.urdf.xacro" />

</robot>
